config/routes.rb
Synesthetic::Application.routes.draw do

  resource :account, :only => [:show]
  scope "account" do
    get :login, :as => :login, :to => "accounts#new"
    post :login, :to => "accounts#create"
    get :logout, :as => :logout, :to => "accounts#destroy"
  end

  resource :letters, :only => [:edit, :update]

  resource :dimensions, :only => [:update]

  resources :texts, :except => :destroy

  root :to => "accounts#show"

end

app/models/colour.rb
class Colour

  def self.random_set
    options = []

    segments = ["00", "33", "66", "99", "CC", "FF"]

    segments.each do |a|
      segments.each do |b|
        segments.each do |c|
          options << "#%s%s%s" % [a, b, c] unless (a == b && b == c)
        end
      end
    end

    options.sort_by{ rand }[1..26]
  end

end

app/models/dimension.rb
class Dimension < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user

  DEFAULT_ATTRIBUTES = { :width => 20, :height => 20, :top => 10, :left => 5, :bottom => 10, :right => 5 }

  def self.default(attributes = {})
    new(DEFAULT_ATTRIBUTES.merge(attributes))
  end

end

app/models/letter.rb
class Letter < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user
  validates_presence_of :letter
  validates_presence_of :colour

end

app/models/text.rb
class Text < ActiveRecord::Base

  belongs_to :user

  validates_presence_of :user
  validates_presence_of :text

  DEFAULT_ATTRIBUTES = { :text => "The quick brown fox jumps over the lazy dog" }

  def self.default(attributes = {})
    new(DEFAULT_ATTRIBUTES.merge(attributes))
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :letters
  has_many :texts

  has_one :dimension

  def dimensions
    dimension || Dimension.default(:user => self)
  end

  validates_presence_of :username

  LETTERS = "a".."z"

  def random_set
    Hash[*LETTERS.zip(Colour.random_set).flatten]
  end

  def letter_map
    map = random_set
    letters.each do |letter|
      map[letter.letter] = letter.colour if map.has_key?(letter.letter) && letter.colour.present?
    end
    map
  end

end

app/controllers/account_controller.rb
class AccountController < ApplicationController

  before_filter :require_user, :except => [:login]

  def index

  end

  def login
    if params[:username].present?
      session[:user_id] = User.find_or_create_by_username(params[:username])

      redirect_to account_path
    end
  end

  def logout
    session[:user_id] = nil

    redirect_to login_path
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :require_user, :except => [:new, :create]

  def show
  end

  def new
  end

  def create
    if params[:username].present?
      session[:user_id] = User.find_or_create_by_username(params[:username])

      redirect_to account_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to login_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  before_filter :require_user

  helper :all

  helper_method :current_user

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def require_user
      redirect_to login_path unless current_user
    end

end

app/controllers/dimensions_controller.rb
class DimensionsController < ApplicationController

  def update
    @dimensions = current_user.dimensions

    @dimensions.attributes = params[:dimension]

    if @dimensions.save
      flash[:notice] = "Dimensions updated"
      redirect_to :back
    else
      flash[:alert] = "Unable to update dimensions"
      redirect_to :back
    end
  end

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController

  def edit
    @letter_map = current_user.letter_map
  end

  def update
    current_user.letter_map.each do |letter, colour|
      if params[:letters][letter].present?
        obj = Letter.find_or_create_by_user_id_and_letter(current_user.id, letter)
        obj.update_attribute(:colour, params[:letters][letter])
      end
    end

    flash[:notice] = "Letters updated"

    redirect_to edit_letters_path
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @texts = current_user.texts

    @default_text = Text.default
  end

  def show
    @letter_map = current_user.letter_map

    @dimensions = current_user.dimensions

    @text = current_user.texts.find(params[:id])
  end

  def new
    @text = current_user.texts.new

    @text.text = Text.default.text
  end

  def edit
    @text = current_user.texts.find(params[:id])
  end

  def create
    @text = current_user.texts.new
    @text.attributes = params[:text]

    if @text.save
      flash[:notice] = "Text created"
      redirect_to @text
    else
      flash[:alert] = "Unable to create text"
      render :new
    end
  end

  def update
    @text = current_user.texts.find(params[:id])
    @text.attributes = params[:text]

    if @text.save
      flash[:notice] = "Text updated"
      redirect_to @text
    else
      flash[:alert] = "Unable to update text"
      render :edit
    end
  end

  def destroy
    @text = current_user.texts.find(params[:id])

    if @text.destroy
      flash[:notice] = "Text deleted"
      redirect_to texts_path
    else
      flash[:alert] = "Unable to delete text"
      redirect_to texts_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def letters
    User::LETTERS
  end

end

app/helpers/text_helper.rb
module TextHelper

  def text_to_classes(text)
    text.each_char.collect do |char|
      if char =~ /[a-zA-Z]/
        ('<span class="letter_%s">&nbsp;</span>' % char.downcase)
      else
        ('<span class="other">%s</span>' % char)
      end
    end.join('').html_safe
  end

end

app/views/accounts/new.html.erb
<%= form_tag login_path do %>

  <%= label_tag :username %>
  <%= text_field_tag :username %>

  <%= submit_tag "Log in" %>

<% end %>

app/views/accounts/show.html.erb
Welcome, <%= current_user.username %>

app/views/dimensions/_form.html.erb
<div>
  Dimensions:
  <%= f.text_field :width %> width
  <%= f.text_field :height %> height
</div>

<div>
  Margin:
  <%= f.text_field :top %> top
  <%= f.text_field :left %> left
  <%= f.text_field :bottom %> bottom
  <%= f.text_field :right %> right
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Synesthetic</title>
    <%= stylesheet_link_tag "application.css" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <ul id="nav">
      <% if current_user %>
        <li><%= link_to "Letters", edit_letters_path %></li>
        <li><%= link_to "Texts", texts_path %></li>
        <li><%= link_to "Log out", logout_path %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
    <%= yield %>
    <%= javascript_include_tag "jquery-1.4.4.min.js" %>
    <%= javascript_include_tag "raphael-min.js" %>
    <%= javascript_include_tag "colorwheel.js" %>
    <%= javascript_include_tag "application.js" %>
  </body>
</html>

app/views/letters/edit.html.erb
<%= form_tag(letters_path, { :method => :put }) do %>

  <div id="letters">
    <% @letter_map.each do |letter, colour| %>
      <div id="letter_<%= letter %>_container" class="container">
        <h2><%= label_tag "letter_#{letter}", letter.upcase %></h2>
        <%= text_field_tag "letters[#{letter}]", colour, :id => "letter_#{letter}" %>
        <div class="colorwheel"></div>
      </div>
    <% end %>
  </div>

  <%= submit_tag "Update colours" %>

<% end %>

app/views/letters/index.html.erb
<%= form_tag update_letters_path do %>

  <% @letter_map.each do |letter, colour| %>
    <%= label_tag "letter_#{letter}", letter.upcase %>
    <%= text_field_tag "letters[#{letter}]", colour, :id => "letter_#{letter}" %>
    <br />
  <% end %>

  <%= submit_tag "Update colours" %>

<% end %>

app/views/texts/_form.html.erb
<div>
  <%= f.text_area :text %>
</div>

app/views/texts/edit.html.erb
<%= form_for @text do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <%= submit_tag "Update text" %>

<% end %>

app/views/texts/index.html.erb
<ul>
  <li><%= link_to "New text", new_text_path %></li>
</ul>

<ul>
  <% @texts.each do |text| %>
    <li><%= link_to truncate(text.text, :length => 30), text %></li>
  <% end %>
</ul>

app/views/texts/new.html.erb
<%= form_for @text do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <%= submit_tag "Create text" %>

<% end %>

app/views/texts/show.html.erb
<style type="text/css">
<% @letter_map.each do |letter, colour| %>
#text .letter_<%= letter %> { background-color: <%= colour %>; }
<% end %>
</style>

<div id="text">
<%= text_to_classes(@text.text) %>
</div>

<div style="clear: both">
  <%= link_to("Edit text", [:edit, @text]) unless @text.new_record? %>
</div>

<div style="clear: both">
  <%= form_for(@dimensions, :url => dimensions_path, :html => { :method => :put, :id => "dimensions" }) do |f| %>

    <%= render :partial => "dimensions/form", :locals => { :f => f } %>

    <%= submit_tag "Update dimensions" %>

  <% end %>
</div>